language: elixir
elixir:
  - 1.3.4
addons:
  postgresql: '9.5'
env:
  - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
# See: github.com/dwyl/repo-badges#documentation
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
